// App constants and theme configuration - Luxury Edition with Teal & Gold

export const COLORS = {
    // Primary - Deep Midnight Charcoal (Background)
    primary: '#1A1A1A',
    primaryDark: '#0D0D0D',
    primaryLight: '#2C2C2C',

    // Accent - Brushed Antique Gold
    accent: '#D4AF37',
    accentDark: '#B8962E',
    accentLight: '#E5C76B',

    // Secondary - Teal-Blue (#4F7C82)
    secondary: '#4F7C82',
    secondaryDark: '#3A5F65',

    // Copper accent
    copper: '#A05E3C',

    // Background - Deep Midnight Charcoal
    background: '#1A1A1A',
    backgroundDark: '#0D0D0D',
    surface: '#2C2C2C',
    surfaceDark: '#1F1F1F',

    // Text - Soft Ivory/Cream
    text: '#FFF8DC',
    textSecondary: '#C0C0C0',
    textLight: '#A0A0A0',
    textMuted: '#8A8A8A',
    textDark: '#F9FAFB',

    // Status
    error: '#E57373',
    errorDark: '#EF4444',
    success: '#81C784',
    warning: '#FFB74D',

    // Borders
    border: 'rgba(212, 175, 55, 0.2)',
    borderDark: 'rgba(212, 175, 55, 0.3)',

    // Misc
    white: '#FFFFFF',
    black: '#000000',

    // Gradients (for references)
    goldGradient: ['#D4AF37', '#B8962E'],
    navyGradient: ['#1a2744', '#0f1a2e'],
    tealGradient: ['#4F7C82', '#1F4529'],
};

export const SPACING = {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
};

export const FONT_SIZES = {
    h1: 28,
    h2: 24,
    h3: 20,
    h4: 18,
    body: 16,
    bodySmall: 14,
    caption: 12,
};

export const BORDER_RADIUS = {
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
    round: 9999,
};

export const DURATION_OPTIONS = [
    { label: '1 Hour', value: '1hour', minutes: 60 },
    { label: '2 Hours', value: '2hours', minutes: 120 },
    { label: '4 Hours', value: '4hours', minutes: 240 },
    { label: '1 Day', value: '1day', minutes: 1440 },
    { label: '2 Days', value: '2days', minutes: 2880 },
    { label: 'Custom', value: 'custom', minutes: 0 },
];

export const MESSAGES = {
    // Auth
    LOGIN_SUCCESS: 'Login successful!',
    REGISTER_SUCCESS: 'Registration successful!',
    LOGOUT_SUCCESS: 'Logged out successfully',

    // QR Generation
    QR_GENERATED: 'QR Code generated successfully!',
    QR_DEACTIVATED: 'QR Code deactivated',

    // QR Scanning
    ATTENDANCE_MARKED: 'Attendance marked successfully!',
    QR_EXPIRED: 'QR Code has expired. Please ask teacher for a new code.',
    ALREADY_MARKED: 'You have already marked attendance for this session.',
    INVALID_QR: 'Invalid QR Code - Not generated by this system or code is corrupted.',
    OUT_OF_RANGE: 'You are out of the allowed location range. Please be at the campus.',

    // Errors
    NETWORK_ERROR: 'Network Connection Issue - Check your internet and try again.',
    UNKNOWN_ERROR: 'Something went wrong. Please try again.',
    PERMISSION_DENIED: 'Permission denied',
};

// QR Code token format
export const QR_PREFIX = 'ATTENDIFY';

// College Information
export const COLLEGE_INFO = {
    name: 'Suryodaya College of Engineering & Technology, Nagpur',
    address: 'Survey No. 117/1 & 117/3 A, Vihirgaon, Umrer Road, Nagpur - 441204',
    contact: '7588953919',
    website: 'www.suryodaya.edu.in',
    email: 'info@suryodaya.edu.in',
};

// Geofencing coordinates (Nagpur campus)
export const CAMPUS_LOCATION = {
    latitude: 21.1498,
    longitude: 79.0806,
    radius: 0.01, // approximately 1km
};